// EZY ZIP Products Seeder Data
// All 41 products matching frontend ezyZipProducts.ts

const ezyZipProducts = [
  // KITCHEN & DINING (12 Products)
  {
    name: '2 IN 1 FORK',
    description: 'Multi-purpose dining utensil combining fork and spoon functionality. Perfect for meals on the go or compact dining.',
    price: 12.99,
    originalPrice: 18.99,
    category: 'Kitchen & Dining',
    image: '/products/2%20IN%201%20FORK/2%20in%201%20fork.jpg',
    images: JSON.stringify([
      '/products/2%20IN%201%20FORK/2%20in%201%20fork.jpg',
      '/products/2%20IN%201%20FORK/2%20in%201%20fork%20angle%202.jpg',
      '/products/2%20IN%201%20FORK/2%20in%201%20fork%20angle%203.jpg',
    ]),
    stock: 50,
    rating: 4.5,
    reviews: 89,
    inStock: true,
    isNew: true,
    isSale: true,
    discount: 32,
    colors: JSON.stringify(['Silver', 'Black']),
    sizes: JSON.stringify([]),
    featured: true
  },
  {
    name: 'CAKE PIE SERVER',
    description: 'Premium cake and pie server with ergonomic handle. Perfect for serving desserts at parties and gatherings.',
    price: 14.99,
    originalPrice: 22.99,
    category: 'Kitchen & Dining',
    image: '/products/CAKE%20PIE%20SERVER/cake%20server.jpg',
    images: JSON.stringify([
      '/products/CAKE%20PIE%20SERVER/cake%20server.jpg',
      '/products/CAKE%20PIE%20SERVER/cake%20server%20banner%201.jpg',
      '/products/CAKE%20PIE%20SERVER/cake%20server%20banner%202.jpg',
    ]),
    stock: 45,
    rating: 4.7,
    reviews: 124,
    inStock: true,
    isNew: false,
    isSale: true,
    discount: 35,
    colors: JSON.stringify(['Silver']),
    sizes: JSON.stringify([]),
    featured: true
  },
  {
    name: 'CHINESE SPOON',
    description: 'Traditional Asian dining spoon, perfect for soups and rice dishes. Durable and dishwasher safe.',
    price: 8.99,
    originalPrice: null,
    category: 'Kitchen & Dining',
    image: '/products/CHINESE%20SPOON/chinese%20spoon.jpg',
    images: JSON.stringify([
      '/products/CHINESE%20SPOON/chinese%20spoon.jpg',
      '/products/CHINESE%20SPOON/chinese%20spoon%20angle%202.jpg',
    ]),
    stock: 100,
    rating: 4.3,
    reviews: 67,
    inStock: true,
    isNew: false,
    isSale: false,
    discount: null,
    colors: JSON.stringify(['White', 'Silver']),
    sizes: JSON.stringify([]),
    featured: false
  },
  {
    name: 'CUTTING BOARD',
    description: 'Premium bamboo cutting board with juice groove. Eco-friendly, knife-friendly surface for all your food prep needs.',
    price: 24.99,
    originalPrice: 34.99,
    category: 'Kitchen & Dining',
    image: '/products/CUTTING%20BOARD/cutting%20board.jpg',
    images: JSON.stringify([
      '/products/CUTTING%20BOARD/cutting%20board.jpg',
      '/products/CUTTING%20BOARD/cutting%20board%20banner%201.jpg',
      '/products/CUTTING%20BOARD/cutting%20board%20banner%202.jpg',
    ]),
    stock: 35,
    rating: 4.8,
    reviews: 234,
    inStock: true,
    isNew: true,
    isSale: true,
    discount: 29,
    colors: JSON.stringify(['Natural']),
    sizes: JSON.stringify(['Small', 'Medium', 'Large']),
    featured: true
  },
  {
    name: 'DISHWASH SCRUBBER',
    description: 'Durable kitchen scrubber for tough stains. Non-scratch surface safe for all cookware.',
    price: 6.99,
    originalPrice: null,
    category: 'Kitchen & Dining',
    image: '/products/DISHWASH%20SCRUBBER/dishwash%20scrubber.jpg',
    images: JSON.stringify([
      '/products/DISHWASH%20SCRUBBER/dishwash%20scrubber.jpg',
      '/products/DISHWASH%20SCRUBBER/dishwash%20scrubber%20banner%201.jpg',
    ]),
    stock: 150,
    rating: 4.4,
    reviews: 156,
    inStock: true,
    isNew: false,
    isSale: false,
    discount: null,
    colors: JSON.stringify(['Green', 'Blue']),
    sizes: JSON.stringify([]),
    featured: false
  },
  {
    name: 'FRUIT SLICER',
    description: 'Multi-blade fruit slicer for quick and even cuts. Perfect for apples, pears, and other fruits.',
    price: 16.99,
    originalPrice: 24.99,
    category: 'Kitchen & Dining',
    image: '/products/FRUIT%20SLICER/fruit%20slicer.jpg',
    images: JSON.stringify([
      '/products/FRUIT%20SLICER/fruit%20slicer.jpg',
      '/products/FRUIT%20SLICER/fruit%20slicer%20banner%201.jpg',
      '/products/FRUIT%20SLICER/fruit%20slicer%20banner%202.jpg',
    ]),
    stock: 60,
    rating: 4.6,
    reviews: 198,
    inStock: true,
    isNew: true,
    isSale: true,
    discount: 32,
    colors: JSON.stringify(['White', 'Green']),
    sizes: JSON.stringify([]),
    featured: true
  },
  {
    name: 'GLASS STORAGE JAR',
    description: 'Airtight glass storage jar with bamboo lid. Perfect for keeping dry goods fresh and organized.',
    price: 19.99,
    originalPrice: null,
    category: 'Kitchen & Dining',
    image: '/products/GLASS%20STORAGE%20JAR/glass%20storage%20jar.jpg',
    images: JSON.stringify([
      '/products/GLASS%20STORAGE%20JAR/glass%20storage%20jar.jpg',
      '/products/GLASS%20STORAGE%20JAR/glass%20storage%20jar%20angle%201.jpg',
    ]),
    stock: 40,
    rating: 4.7,
    reviews: 143,
    inStock: true,
    isNew: false,
    isSale: false,
    discount: null,
    colors: JSON.stringify(['Clear']),
    sizes: JSON.stringify(['500ml', '1000ml', '1500ml']),
    featured: false
  },
  {
    name: 'KITCHEN BAMBOO CLOTH CLEANER',
    description: 'Eco-friendly bamboo cloth for kitchen cleaning. Reusable, washable, and highly absorbent.',
    price: 11.99,
    originalPrice: 16.99,
    category: 'Kitchen & Dining',
    image: '/products/KITCHEN%20BAMBOO%20CLOTH%20CLEANER/Bamboo%20kitchen%20cleaner%20cloth.jpg',
    images: JSON.stringify([
      '/products/KITCHEN%20BAMBOO%20CLOTH%20CLEANER/Bamboo%20kitchen%20cleaner%20cloth.jpg',
      '/products/KITCHEN%20BAMBOO%20CLOTH%20CLEANER/Bamboo%20kitchen%20cleaner%20cloth%20angle%201.jpg',
    ]),
    stock: 80,
    rating: 4.5,
    reviews: 87,
    inStock: true,
    isNew: false,
    isSale: true,
    discount: 29,
    colors: JSON.stringify(['Natural', 'White']),
    sizes: JSON.stringify([]),
    featured: false
  },
  {
    name: 'LADLES SERVING SPOON',
    description: 'Stainless steel serving ladle with comfortable grip. Perfect for soups, stews, and sauces.',
    price: 13.99,
    originalPrice: null,
    category: 'Kitchen & Dining',
    image: '/products/LADLES%20SERVING%20SPOON/ladles%20serving%20spoon.jpg',
    images: JSON.stringify([
      '/products/LADLES%20SERVING%20SPOON/ladles%20serving%20spoon.jpg',
      '/products/LADLES%20SERVING%20SPOON/ladles%20serving%20spoon%20angle%201.jpg',
    ]),
    stock: 55,
    rating: 4.6,
    reviews: 112,
    inStock: true,
    isNew: false,
    isSale: false,
    discount: null,
    colors: JSON.stringify(['Silver']),
    sizes: JSON.stringify([]),
    featured: false
  },
  {
    name: 'LONG HANDLE SPOON',
    description: 'Extra-long handle spoon for deep pots and jars. Heat-resistant and dishwasher safe.',
    price: 10.99,
    originalPrice: null,
    category: 'Kitchen & Dining',
    image: '/products/LONG%20HANDLE%20SPOON/long%20handle%20spoon.jpg',
    images: JSON.stringify([
      '/products/LONG%20HANDLE%20SPOON/long%20handle%20spoon.jpg',
      '/products/LONG%20HANDLE%20SPOON/long%20handle%20spoon%20angle.jpg',
    ]),
    stock: 70,
    rating: 4.4,
    reviews: 76,
    inStock: true,
    isNew: false,
    isSale: false,
    discount: null,
    colors: JSON.stringify(['Silver', 'Black']),
    sizes: JSON.stringify([]),
    featured: false
  },
  {
    name: 'STAINLESS SCRUBBER',
    description: 'Heavy-duty stainless steel scrubber for tough cleaning jobs. Rust-resistant and long-lasting.',
    price: 7.99,
    originalPrice: null,
    category: 'Kitchen & Dining',
    image: '/products/STAINLESS%20SCRUBBER/Stainless%20scrubber.jpg',
    images: JSON.stringify([
      '/products/STAINLESS%20SCRUBBER/Stainless%20scrubber.jpg',
      '/products/STAINLESS%20SCRUBBER/Stainless%20scrubber%20banner%201.jpg',
    ]),
    stock: 120,
    rating: 4.3,
    reviews: 94,
    inStock: true,
    isNew: false,
    isSale: false,
    discount: null,
    colors: JSON.stringify(['Silver']),
    sizes: JSON.stringify([]),
    featured: false
  },
  {
    name: 'COTTON KITCHEN CLOTH',
    description: 'Pack of 3 premium cotton kitchen towels. Super absorbent and machine washable.',
    price: 9.99,
    originalPrice: 14.99,
    category: 'Kitchen & Dining',
    image: '/products/COTTON%20KITCHEN%20CLOTH/Kitchen%20cloth%20angle%201.jpg',
    images: JSON.stringify([
      '/products/COTTON%20KITCHEN%20CLOTH/Kitchen%20cloth%20angle%201.jpg',
      '/products/COTTON%20KITCHEN%20CLOTH/Kitchen%20cloth%20angle%202.jpg',
    ]),
    stock: 90,
    rating: 4.5,
    reviews: 145,
    inStock: true,
    isNew: false,
    isSale: true,
    discount: 33,
    colors: JSON.stringify(['White', 'Gray', 'Beige']),
    sizes: JSON.stringify([]),
    featured: false
  },

  // PERSONAL CARE (8 Products)
  {
    name: 'BAMBOO HAIR BRUSH',
    description: 'Eco-friendly bamboo hair brush with natural bristles. Gentle on hair and scalp, reduces static.',
    price: 18.99,
    originalPrice: 26.99,
    category: 'Personal Care',
    image: '/products/BAMBOO HAIR BRUSH/BAMBOO HAIR BRUSH ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/BAMBOO HAIR BRUSH/BAMBOO HAIR BRUSH ANGLE 1.jpg',
      '/products/BAMBOO HAIR BRUSH/BAMBOO HAIR BRUSH ANGLE 2.jpg',
      '/products/BAMBOO HAIR BRUSH/BAMBOO HAIR BRUSH ANGLE 3.jpg',
    ]),
    stock: 65,
    rating: 4.8,
    reviews: 267,
    inStock: true,
    isNew: true,
    isSale: true,
    discount: 30,
    colors: JSON.stringify(['Natural']),
    sizes: JSON.stringify([]),
    featured: true
  },
  {
    name: 'BOAR BRISTLE ROUND HAIR BRUSH',
    description: 'Premium boar bristle round brush for blow-drying and styling. Creates volume and shine.',
    price: 24.99,
    originalPrice: 34.99,
    category: 'Personal Care',
    image: '/products/BOAR BRISTLE ROUND HAIR BRUSH/BOAR BRISTLE ROUND HAIR BRUSH ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/BOAR BRISTLE ROUND HAIR BRUSH/BOAR BRISTLE ROUND HAIR BRUSH ANGLE 1.jpg',
      '/products/BOAR BRISTLE ROUND HAIR BRUSH/BOAR BRISTLE ROUND HAIR BRUSH ANGLE 2.jpg',
    ]),
    stock: 40,
    rating: 4.9,
    reviews: 189,
    inStock: true,
    isNew: true,
    isSale: true,
    discount: 29,
    colors: JSON.stringify(['Wood']),
    sizes: JSON.stringify(['Small', 'Medium', 'Large']),
    featured: true
  },
  {
    name: 'BODY MASSAGER',
    description: 'Handheld body massager with multiple massage nodes. Relieves muscle tension and promotes relaxation.',
    price: 29.99,
    originalPrice: 44.99,
    category: 'Personal Care',
    image: '/products/BODY MASSAGER/BODY MASSAGER ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/BODY MASSAGER/BODY MASSAGER ANGLE 1.jpg',
      '/products/BODY MASSAGER/BODY MASSAGER ANGLE 2.jpg',
      '/products/BODY MASSAGER/BODY MASSAGER ANGLE 3.jpg',
    ]),
    stock: 30,
    rating: 4.7,
    reviews: 156,
    inStock: true,
    isNew: false,
    isSale: true,
    discount: 33,
    colors: JSON.stringify(['Blue', 'Pink', 'Black']),
    sizes: JSON.stringify([]),
    featured: true
  },
  {
    name: 'DETANGLING TRAVEL BRUSH',
    description: 'Compact travel brush with flexible bristles for painless detangling. Perfect for on-the-go styling.',
    price: 14.99,
    originalPrice: null,
    category: 'Personal Care',
    image: '/products/DETANGLING TRAVEL BRUSH/DETANGLING TRAVEL BRUSH ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/DETANGLING TRAVEL BRUSH/DETANGLING TRAVEL BRUSH ANGLE 1.jpg',
      '/products/DETANGLING TRAVEL BRUSH/DETANGLING TRAVEL BRUSH ANGLE 2.jpg',
    ]),
    stock: 75,
    rating: 4.6,
    reviews: 234,
    inStock: true,
    isNew: true,
    isSale: false,
    discount: null,
    colors: JSON.stringify(['Pink', 'Blue', 'Purple']),
    sizes: JSON.stringify([]),
    featured: false
  },
  {
    name: 'MASSAGER BODY BRUSH',
    description: 'Dual-purpose body brush and massager. Exfoliates skin and improves circulation.',
    price: 19.99,
    originalPrice: 28.99,
    category: 'Personal Care',
    image: '/products/MASSAGER BODY BRUSH/MASSAGER BODY BRUSH ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/MASSAGER BODY BRUSH/MASSAGER BODY BRUSH ANGLE 1.jpg',
      '/products/MASSAGER BODY BRUSH/MASSAGER BODY BRUSH ANGLE 2.jpg',
    ]),
    stock: 50,
    rating: 4.5,
    reviews: 123,
    inStock: true,
    isNew: false,
    isSale: true,
    discount: 31,
    colors: JSON.stringify(['Natural', 'Pink']),
    sizes: JSON.stringify([]),
    featured: false
  },
  {
    name: 'MINI HAIR BRUSH',
    description: 'Pocket-sized hair brush perfect for purses and travel bags. Folds for compact storage.',
    price: 11.99,
    originalPrice: null,
    category: 'Personal Care',
    image: '/products/MINI HAIR BRUSH/MINI HAIR BRUSH ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/MINI HAIR BRUSH/MINI HAIR BRUSH ANGLE 1.jpg',
      '/products/MINI HAIR BRUSH/MINI HAIR BRUSH ANGLE 2.jpg',
    ]),
    stock: 100,
    rating: 4.4,
    reviews: 198,
    inStock: true,
    isNew: false,
    isSale: false,
    discount: null,
    colors: JSON.stringify(['Black', 'Pink', 'White']),
    sizes: JSON.stringify([]),
    featured: false
  },
  {
    name: 'PUMICE STONE',
    description: 'Natural volcanic pumice stone for foot care. Removes calluses and dead skin effectively.',
    price: 8.99,
    originalPrice: null,
    category: 'Personal Care',
    image: '/products/PUMICE STONE/PUMICE STONE ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/PUMICE STONE/PUMICE STONE ANGLE 1.jpg',
      '/products/PUMICE STONE/PUMICE STONE ANGLE 2.jpg',
    ]),
    stock: 85,
    rating: 4.3,
    reviews: 167,
    inStock: true,
    isNew: false,
    isSale: false,
    discount: null,
    colors: JSON.stringify(['Gray']),
    sizes: JSON.stringify([]),
    featured: false
  },
  {
    name: 'STYLING BRUSH',
    description: 'Professional styling brush with heat-resistant bristles. Ideal for blow-drying and styling.',
    price: 16.99,
    originalPrice: 23.99,
    category: 'Personal Care',
    image: '/products/STYLING BRUSH/STYLING BRUSH ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/STYLING BRUSH/STYLING BRUSH ANGLE 1.jpg',
      '/products/STYLING BRUSH/STYLING BRUSH ANGLE 2.jpg',
    ]),
    stock: 60,
    rating: 4.7,
    reviews: 145,
    inStock: true,
    isNew: true,
    isSale: true,
    discount: 29,
    colors: JSON.stringify(['Black', 'Pink']),
    sizes: JSON.stringify([]),
    featured: true
  },
  {
    name: 'RETRACTABLE HAIR BRUSH',
    description: 'Innovative retractable hair brush for travel. Compact design with protective cover.',
    price: 14.99,
    originalPrice: null,
    category: 'Personal Care',
    image: '/products/RETRACTABLE HAIR BRUSH/RETRACTABLE HAIR BRUSH ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/RETRACTABLE HAIR BRUSH/RETRACTABLE HAIR BRUSH ANGLE 1.jpg',
      '/products/RETRACTABLE HAIR BRUSH/RETRACTABLE HAIR BRUSH ANGLE 2.jpg',
    ]),
    stock: 55,
    rating: 4.5,
    reviews: 156,
    inStock: true,
    isNew: true,
    isSale: false,
    discount: null,
    colors: JSON.stringify(['Pink', 'Black', 'Purple']),
    sizes: JSON.stringify([]),
    featured: false
  },

  // HYDRATION (6 Products)
  {
    name: 'STAINLESS STEEL WATER BOTTLE',
    description: 'Premium double-wall insulated water bottle. Keeps drinks cold for 24 hours, hot for 12 hours.',
    price: 32.99,
    originalPrice: 44.99,
    category: 'Hydration',
    image: '/products/STAINLESS STEEL WATER BOTTLE/STAINLESS STEEL WATER BOTTLE ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/STAINLESS STEEL WATER BOTTLE/STAINLESS STEEL WATER BOTTLE ANGLE 1.jpg',
      '/products/STAINLESS STEEL WATER BOTTLE/STAINLESS STEEL WATER BOTTLE ANGLE 2.jpg',
      '/products/STAINLESS STEEL WATER BOTTLE/STAINLESS STEEL WATER BOTTLE ANGLE 3.jpg',
    ]),
    stock: 70,
    rating: 4.9,
    reviews: 456,
    inStock: true,
    isNew: true,
    isSale: true,
    discount: 27,
    colors: JSON.stringify(['Black', 'Silver', 'Blue', 'Pink']),
    sizes: JSON.stringify(['500ml', '750ml', '1000ml']),
    featured: true
  },
  {
    name: 'TUMBLER',
    description: 'Insulated tumbler with lid and straw. Perfect for hot or cold beverages on the go.',
    price: 24.99,
    originalPrice: 32.99,
    category: 'Hydration',
    image: '/products/TUMBLER/TUMBLER ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/TUMBLER/TUMBLER ANGLE 1.jpg',
      '/products/TUMBLER/TUMBLER ANGLE 2.jpg',
    ]),
    stock: 60,
    rating: 4.7,
    reviews: 289,
    inStock: true,
    isNew: false,
    isSale: true,
    discount: 24,
    colors: JSON.stringify(['Black', 'White', 'Red', 'Blue']),
    sizes: JSON.stringify(['20oz', '30oz']),
    featured: true
  },
  {
    name: 'WATER BOTTLE',
    description: 'BPA-free plastic water bottle with leak-proof cap. Lightweight and perfect for sports.',
    price: 15.99,
    originalPrice: null,
    category: 'Hydration',
    image: '/products/WATER BOTTLE/WATER BOTTLE ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/WATER BOTTLE/WATER BOTTLE ANGLE 1.jpg',
      '/products/WATER BOTTLE/WATER BOTTLE ANGLE 2.jpg',
    ]),
    stock: 120,
    rating: 4.4,
    reviews: 567,
    inStock: true,
    isNew: false,
    isSale: false,
    discount: null,
    colors: JSON.stringify(['Clear', 'Blue', 'Green', 'Pink']),
    sizes: JSON.stringify(['500ml', '750ml', '1000ml']),
    featured: false
  },
  {
    name: 'WATER DISPENSER',
    description: 'Desktop water dispenser with hot and cold options. Perfect for home or office use.',
    price: 89.99,
    originalPrice: 129.99,
    category: 'Hydration',
    image: '/products/WATER DISPENSER/WATER DISPENSER ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/WATER DISPENSER/WATER DISPENSER ANGLE 1.jpg',
      '/products/WATER DISPENSER/WATER DISPENSER ANGLE 2.jpg',
    ]),
    stock: 15,
    rating: 4.6,
    reviews: 178,
    inStock: true,
    isNew: true,
    isSale: true,
    discount: 31,
    colors: JSON.stringify(['White', 'Black']),
    sizes: JSON.stringify([]),
    featured: true
  },
  {
    name: 'WHISKEY GLASS PERSONALISED',
    description: 'Premium crystal whiskey glass with personalization option. Perfect gift for whiskey lovers.',
    price: 34.99,
    originalPrice: 49.99,
    category: 'Hydration',
    image: '/products/WHISKEY GLASS PERSONALISED/WHISKEY GLASS PERSONALISED ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/WHISKEY GLASS PERSONALISED/WHISKEY GLASS PERSONALISED ANGLE 1.jpg',
      '/products/WHISKEY GLASS PERSONALISED/WHISKEY GLASS PERSONALISED ANGLE 2.jpg',
    ]),
    stock: 35,
    rating: 4.8,
    reviews: 134,
    inStock: true,
    isNew: true,
    isSale: true,
    discount: 30,
    colors: JSON.stringify(['Clear']),
    sizes: JSON.stringify([]),
    featured: true
  },
  {
    name: 'WHISKY GLASS',
    description: 'Set of 2 premium whisky glasses with thick base. Perfect weight and balance for whisky enjoyment.',
    price: 28.99,
    originalPrice: null,
    category: 'Hydration',
    image: '/products/WHISKY GLASS/WHISKY GLASS ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/WHISKY GLASS/WHISKY GLASS ANGLE 1.jpg',
      '/products/WHISKY GLASS/WHISKY GLASS ANGLE 2.jpg',
    ]),
    stock: 40,
    rating: 4.7,
    reviews: 98,
    inStock: true,
    isNew: false,
    isSale: false,
    discount: null,
    colors: JSON.stringify(['Clear']),
    sizes: JSON.stringify([]),
    featured: false
  },

  // BAGS & ACCESSORIES (4 Products)
  {
    name: 'LAPTOP BAG',
    description: 'Professional laptop bag with padded compartment. Fits laptops up to 15.6 inches.',
    price: 49.99,
    originalPrice: 69.99,
    category: 'Bags & Accessories',
    image: '/products/LAPTOP BAG/LAPTOP BAG ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/LAPTOP BAG/LAPTOP BAG ANGLE 1.jpg',
      '/products/LAPTOP BAG/LAPTOP BAG ANGLE 2.jpg',
      '/products/LAPTOP BAG/LAPTOP BAG ANGLE 3.jpg',
    ]),
    stock: 45,
    rating: 4.6,
    reviews: 234,
    inStock: true,
    isNew: true,
    isSale: true,
    discount: 29,
    colors: JSON.stringify(['Black', 'Gray', 'Navy']),
    sizes: JSON.stringify(['13-14 inch', '15-16 inch']),
    featured: true
  },
  {
    name: 'WATERPROOF MINI BAG',
    description: 'Compact waterproof bag perfect for beach trips, boating, or outdoor activities.',
    price: 22.99,
    originalPrice: 29.99,
    category: 'Bags & Accessories',
    image: '/products/WATERPROOF MINI BAG/WATERPROOF MINI BAG ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/WATERPROOF MINI BAG/WATERPROOF MINI BAG ANGLE 1.jpg',
      '/products/WATERPROOF MINI BAG/WATERPROOF MINI BAG ANGLE 2.jpg',
    ]),
    stock: 55,
    rating: 4.5,
    reviews: 167,
    inStock: true,
    isNew: false,
    isSale: true,
    discount: 23,
    colors: JSON.stringify(['Blue', 'Yellow', 'Black']),
    sizes: JSON.stringify([]),
    featured: false
  },
  {
    name: 'WATERPROOF TOTE BAG',
    description: 'Large waterproof tote bag with multiple pockets. Perfect for shopping, beach, or gym.',
    price: 34.99,
    originalPrice: 49.99,
    category: 'Bags & Accessories',
    image: '/products/WATERPROOF TOTE BAG/WATERPROOF TOTE BAG ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/WATERPROOF TOTE BAG/WATERPROOF TOTE BAG ANGLE 1.jpg',
      '/products/WATERPROOF TOTE BAG/WATERPROOF TOTE BAG ANGLE 2.jpg',
    ]),
    stock: 40,
    rating: 4.7,
    reviews: 189,
    inStock: true,
    isNew: true,
    isSale: true,
    discount: 30,
    colors: JSON.stringify(['Black', 'Navy', 'Gray']),
    sizes: JSON.stringify([]),
    featured: true
  },
  {
    name: 'TOWEL',
    description: 'Premium microfiber towel - quick-drying and super absorbent. Perfect for gym, beach, or travel.',
    price: 19.99,
    originalPrice: null,
    category: 'Bags & Accessories',
    image: '/products/TOWEL/TOWEL ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/TOWEL/TOWEL ANGLE 1.jpg',
      '/products/TOWEL/TOWEL ANGLE 2.jpg',
    ]),
    stock: 80,
    rating: 4.6,
    reviews: 278,
    inStock: true,
    isNew: false,
    isSale: false,
    discount: null,
    colors: JSON.stringify(['Blue', 'Gray', 'Pink', 'White']),
    sizes: JSON.stringify([]),
    featured: false
  },

  // TECH & ELECTRONICS (3 Products)
  {
    name: 'GAMING KEYBOARD & MOUSE',
    description: 'RGB backlit gaming keyboard and mouse combo. Mechanical switches and programmable buttons.',
    price: 79.99,
    originalPrice: 119.99,
    category: 'Tech & Electronics',
    image: '/products/GAMING KEYBOARD & MOUSE/GAMING KEYBOARD & MOUSE ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/GAMING KEYBOARD & MOUSE/GAMING KEYBOARD & MOUSE ANGLE 1.jpg',
      '/products/GAMING KEYBOARD & MOUSE/GAMING KEYBOARD & MOUSE ANGLE 2.jpg',
      '/products/GAMING KEYBOARD & MOUSE/GAMING KEYBOARD & MOUSE ANGLE 3.jpg',
    ]),
    stock: 35,
    rating: 4.8,
    reviews: 456,
    inStock: true,
    isNew: true,
    isSale: true,
    discount: 33,
    colors: JSON.stringify(['Black']),
    sizes: JSON.stringify([]),
    featured: true
  },
  {
    name: 'GAMING MOUSE',
    description: 'Ergonomic gaming mouse with adjustable DPI and RGB lighting. 6 programmable buttons.',
    price: 39.99,
    originalPrice: 59.99,
    category: 'Tech & Electronics',
    image: '/products/GAMING MOUSE/GAMING MOUSE ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/GAMING MOUSE/GAMING MOUSE ANGLE 1.jpg',
      '/products/GAMING MOUSE/GAMING MOUSE ANGLE 2.jpg',
    ]),
    stock: 50,
    rating: 4.7,
    reviews: 389,
    inStock: true,
    isNew: false,
    isSale: true,
    discount: 33,
    colors: JSON.stringify(['Black', 'White']),
    sizes: JSON.stringify([]),
    featured: true
  },
  {
    name: 'KEYBOARD & MOUSE',
    description: 'Wireless keyboard and mouse combo for office use. Quiet keys and long battery life.',
    price: 44.99,
    originalPrice: 64.99,
    category: 'Tech & Electronics',
    image: '/products/KEYBOARD & MOUSE/KEYBOARD & MOUSE ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/KEYBOARD & MOUSE/KEYBOARD & MOUSE ANGLE 1.jpg',
      '/products/KEYBOARD & MOUSE/KEYBOARD & MOUSE ANGLE 2.jpg',
    ]),
    stock: 45,
    rating: 4.5,
    reviews: 267,
    inStock: true,
    isNew: false,
    isSale: true,
    discount: 31,
    colors: JSON.stringify(['Black', 'White']),
    sizes: JSON.stringify([]),
    featured: false
  },

  // CLEANING & MAINTENANCE (3 Products)
  {
    name: 'BAMBOO DISH SCRUB',
    description: 'Eco-friendly bamboo dish scrubber. Natural, biodegradable, and effective on tough stains.',
    price: 8.99,
    originalPrice: null,
    category: 'Cleaning & Maintenance',
    image: '/products/BAMBOO DISH SCRUB/BAMBOO DISH SCRUB ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/BAMBOO DISH SCRUB/BAMBOO DISH SCRUB ANGLE 1.jpg',
      '/products/BAMBOO DISH SCRUB/BAMBOO DISH SCRUB ANGLE 2.jpg',
    ]),
    stock: 100,
    rating: 4.4,
    reviews: 134,
    inStock: true,
    isNew: false,
    isSale: false,
    discount: null,
    colors: JSON.stringify(['Natural']),
    sizes: JSON.stringify([]),
    featured: false
  },
  {
    name: 'MICROFIBER CLEANING CLOTH',
    description: 'Pack of 5 premium microfiber cloths. Perfect for cleaning glass, electronics, and surfaces.',
    price: 12.99,
    originalPrice: 18.99,
    category: 'Cleaning & Maintenance',
    image: '/products/MICROFIBER CLEANING CLOTH/MICROFIBER CLEANING CLOTH ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/MICROFIBER CLEANING CLOTH/MICROFIBER CLEANING CLOTH ANGLE 1.jpg',
      '/products/MICROFIBER CLEANING CLOTH/MICROFIBER CLEANING CLOTH ANGLE 2.jpg',
    ]),
    stock: 110,
    rating: 4.7,
    reviews: 289,
    inStock: true,
    isNew: false,
    isSale: true,
    discount: 32,
    colors: JSON.stringify(['Mixed Colors']),
    sizes: JSON.stringify([]),
    featured: false
  },

  // SPIRITUAL & CULTURAL (5 Products)
  {
    name: 'AKHAND DEEP',
    description: 'Traditional brass oil lamp (diya) for continuous burning. Perfect for puja and religious ceremonies.',
    price: 45.99,
    originalPrice: 64.99,
    category: 'Spiritual & Cultural',
    image: '/products/AKHAND DEEP/AKHAND DEEP ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/AKHAND DEEP/AKHAND DEEP ANGLE 1.jpg',
      '/products/AKHAND DEEP/AKHAND DEEP ANGLE 2.jpg',
    ]),
    stock: 25,
    rating: 4.9,
    reviews: 98,
    inStock: true,
    isNew: false,
    isSale: true,
    discount: 29,
    colors: JSON.stringify(['Brass']),
    sizes: JSON.stringify([]),
    featured: true
  },
  {
    name: 'AYURVEDIC COPPER BALL',
    description: 'Traditional Ayurvedic copper ball for water purification and health benefits.',
    price: 29.99,
    originalPrice: null,
    category: 'Spiritual & Cultural',
    image: '/products/AYURVEDIC COPPER BALL/AYURVEDIC COPPER BALL ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/AYURVEDIC COPPER BALL/AYURVEDIC COPPER BALL ANGLE 1.jpg',
      '/products/AYURVEDIC COPPER BALL/AYURVEDIC COPPER BALL ANGLE 2.jpg',
    ]),
    stock: 30,
    rating: 4.6,
    reviews: 67,
    inStock: true,
    isNew: false,
    isSale: false,
    discount: null,
    colors: JSON.stringify(['Copper']),
    sizes: JSON.stringify([]),
    featured: false
  },
  {
    name: 'BRAS AKHAND JYOT DIYA',
    description: 'Ornate brass Akhand Jyoti lamp with intricate designs. Traditional temple-style oil lamp.',
    price: 52.99,
    originalPrice: 74.99,
    category: 'Spiritual & Cultural',
    image: '/products/BRAS AKHAND JYOT DIYA/BRAS AKHAND JYOT DIYA ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/BRAS AKHAND JYOT DIYA/BRAS AKHAND JYOT DIYA ANGLE 1.jpg',
      '/products/BRAS AKHAND JYOT DIYA/BRAS AKHAND JYOT DIYA ANGLE 2.jpg',
    ]),
    stock: 20,
    rating: 4.8,
    reviews: 76,
    inStock: true,
    isNew: true,
    isSale: true,
    discount: 29,
    colors: JSON.stringify(['Brass']),
    sizes: JSON.stringify([]),
    featured: true
  },
  {
    name: 'DHOOP DANI',
    description: 'Traditional brass incense holder (dhoop dani) for home puja. Beautiful decorative design.',
    price: 24.99,
    originalPrice: null,
    category: 'Spiritual & Cultural',
    image: '/products/DHOOP DANI/DHOOP DANI ANGLE 1.jpg',
    images: JSON.stringify([
      '/products/DHOOP DANI/DHOOP DANI ANGLE 1.jpg',
      '/products/DHOOP DANI/DHOOP DANI ANGLE 2.jpg',
    ]),
    stock: 35,
    rating: 4.5,
    reviews: 89,
    inStock: true,
    isNew: false,
    isSale: false,
    discount: null,
    colors: JSON.stringify(['Brass']),
    sizes: JSON.stringify([]),
    featured: false
  },
  {
    name: 'PURE BRASS KALASH',
    description: 'Traditional pure brass Kalash (sacred pot) for religious ceremonies and puja rituals.',
    price: 64.99,
    originalPrice: 89.99,
    category: 'Spiritual & Cultural',
    image: '/products/PURE%20BRASS%20KALASH/kalash.jpg',
    images: JSON.stringify([
      '/products/PURE%20BRASS%20KALASH/kalash.jpg',
      '/products/PURE%20BRASS%20KALASH/kalash%20angle%201.jpg',
    ]),
    stock: 18,
    rating: 4.9,
    reviews: 112,
    inStock: true,
    isNew: true,
    isSale: true,
    discount: 28,
    colors: JSON.stringify(['Brass']),
    sizes: JSON.stringify(['Small', 'Medium', 'Large']),
    featured: true
  },
];

// Category definitions
const categories = [
  {
    name: 'Kitchen & Dining',
    slug: 'kitchen-dining',
    description: 'Essential tools and accessories for your kitchen and dining needs',
    isActive: true,
    sortOrder: 1
  },
  {
    name: 'Personal Care',
    slug: 'personal-care',
    description: 'Premium personal care and wellness products',
    isActive: true,
    sortOrder: 2
  },
  {
    name: 'Hydration',
    slug: 'hydration',
    description: 'Stay hydrated with our premium bottles and drinkware',
    isActive: true,
    sortOrder: 3
  },
  {
    name: 'Tech & Electronics',
    slug: 'tech-electronics',
    description: 'Latest technology and electronic accessories',
    isActive: true,
    sortOrder: 4
  },
  {
    name: 'Bags & Accessories',
    slug: 'bags-accessories',
    description: 'Stylish and functional bags and accessories',
    isActive: true,
    sortOrder: 5
  },
  {
    name: 'Spiritual & Cultural',
    slug: 'spiritual-cultural',
    description: 'Traditional spiritual and cultural items for your home',
    isActive: true,
    sortOrder: 6
  },
  {
    name: 'Cleaning & Maintenance',
    slug: 'cleaning-maintenance',
    description: 'Eco-friendly cleaning and maintenance solutions',
    isActive: true,
    sortOrder: 7
  }
];

module.exports = {
  ezyZipProducts,
  categories
};
